name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: test
    runs-on: ubuntu-latest

    # https://docs.github.com/en/enterprise-server@3.2/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root 
          POSTGRES_PASSWORD: secret 
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go # step name

    - name: Run migrations
      run: make migrateup

    - name: Test # 해당 프로젝트에선 알아서 빌드되므로 build step이 필요없음
      run: make test 
